spring:
  application:
    name: Hotel Management

  datasource:
    url: jdbc:postgresql://213.136.80.48:5433/db-hotel?currentSchema=public&stringtype=unspecified
    username: truongdq
    password: 123456
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

#OpenAPI Properties
springdoc:
  api-docs:
    path: /swagger-ui.html
    enabled: true

server:
  port: 9091

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

minio:
  url: http://213.136.80.48:9000
  access-key: nZM1Apuad0ayaACUJo3U
  secret-key: CdchAYDvNoBrWKd8vrAU5lINt9tTKIrXkKsv4TVU
  bucket: hotel


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 18000000
  refresh-token:
    expiration: 86400000

api:
  prefix: /api
